name: ecommerce_beta
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  #flutter_native_splash: ^2.3.0
  flutter_riverpod: ^2.3.2
  formz: ^0.7.0
  go_router: ^8.0.3
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-1.jfif"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/icon/
