name: ecommerce_beta
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.1
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.2
  formz: ^0.7.0
  go_router: ^14.0.2
  google_sign_in: ^6.2.1
  #barcode_scanner: ^4.2.0
  shared_preferences: ^2.0.18
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
   #permission_handler: ^11.3.1
 

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  #flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-1.jfif"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/icon/
