// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKrOH-VEG5w1v-MYXAncS6dY00sz9w4M4',
    appId: '1:933668294266:web:4b12c50c266b6afa08f5c3',
    messagingSenderId: '933668294266',
    projectId: 'flutter-ecommerce-fb692',
    authDomain: 'flutter-ecommerce-fb692.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-fb692.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvDUd_Egz6o-lcyH-JyZD4T1AW5ZzjIZc',
    appId: '1:933668294266:android:f80fc8d91253714508f5c3',
    messagingSenderId: '933668294266',
    projectId: 'flutter-ecommerce-fb692',
    storageBucket: 'flutter-ecommerce-fb692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW_VYjh_Arfw4dL_dU5F5bnVmrsHyeVqY',
    appId: '1:933668294266:ios:96cc8e67be6cb3ff08f5c3',
    messagingSenderId: '933668294266',
    projectId: 'flutter-ecommerce-fb692',
    storageBucket: 'flutter-ecommerce-fb692.appspot.com',
    iosClientId: '933668294266-t9uj680e5qefiajlk0rrmff0i2f90eb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW_VYjh_Arfw4dL_dU5F5bnVmrsHyeVqY',
    appId: '1:933668294266:ios:96cc8e67be6cb3ff08f5c3',
    messagingSenderId: '933668294266',
    projectId: 'flutter-ecommerce-fb692',
    storageBucket: 'flutter-ecommerce-fb692.appspot.com',
    iosClientId: '933668294266-t9uj680e5qefiajlk0rrmff0i2f90eb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKrOH-VEG5w1v-MYXAncS6dY00sz9w4M4',
    appId: '1:933668294266:web:dcf6c9e67abbd0b508f5c3',
    messagingSenderId: '933668294266',
    projectId: 'flutter-ecommerce-fb692',
    authDomain: 'flutter-ecommerce-fb692.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-fb692.appspot.com',
  );

}